spring:
  application:
    name: user-center
  # DataSource Config
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/xaviusercenter
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: is_delete